### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by spereverde** [collective/collective.explicitacquisition#3]
- Functionality seems to work as described in code and test when you run the instance
- But when running the tests (bin/test) 2 out of 3 tests fail
- checked on master branch with Python2.7 and on python3 branch with Python 3.6

~~~
Failure in test test_not_found_when_acquired_content (collective.explicitacquisition.tests.test_bad_acquisition.TestBadAcquisition)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/u0045445/projects/plone/coredev_py3/src/collective.explicitacquisition/collective/explicitacquisition/tests/test_bad_acquisition.py", line 34, in test_not_found_when_acquired_content
    self.assertTrue(
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Acquired content should not be published.

Failure in test test_not_found_when_template_on_acquired_content (collective.explicitacquisition.tests.test_bad_acquisition.TestBadAcquisition)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/u0045445/projects/plone/coredev_py3/src/collective.explicitacquisition/collective/explicitacquisition/tests/test_bad_acquisition.py", line 57, in test_not_found_when_template_on_acquired_content
    msg='Acquired content should not be published.')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Acquired content should not be published.

Ran 3 tests with 2 failures, 0 errors, 0 skipped in 2 minutes 19.623 seconds.
~~~

**Comment by jensens** [comment]
fixed
